import { Logger } from '@nestjs/common';
import { Cache } from 'cache-manager';

/**
 * Configuration for BaseRedisRepository
 */
export interface BaseRedisRepositoryConfig {
  keyPrefix: string;      // Prefix for all keys (e.g., 'slot:reservation')
  defaultTTL: number;     // Default TTL in seconds
  entityName: string;     // Entity name for logging
}

/**
 * Base Redis Repository
 *
 * Abstract class for Redis-backed repositories.
 * Provides CRUD operations with TTL management and consistent key generation.
 *
 * Similar to BaseRepository (PostgreSQL), but for Redis.
 *
 * Features:
 * - Automatic key prefixing
 * - TTL management
 * - Logging
 * - Type-safe operations
 * - Abstract key generation (subclasses define their own logic)
 *
 * @template T - Type of entity to store
 *
 * @example
 * ```typescript
 * @Injectable()
 * export class SlotReservationRepository extends BaseRedisRepository<string> {
 *   constructor(@Inject(CACHE_MANAGER) cacheManager: Cache) {
 *     super(cacheManager, {
 *       keyPrefix: 'slot:reservation',
 *       defaultTTL: 600, // 10 minutes
 *       entityName: 'SlotReservation',
 *     });
 *   }
 *
 *   protected generateKey(businessId: string, teamId: string, scheduledAt: Date): string {
 *     return RedisLockManager.generateLockKey({
 *       businessId,
 *       teamId: teamId || 'no-team',
 *       scheduledAt: scheduledAt.toISOString(),
 *     });
 *   }
 *
 *   async reserveSlot(businessId: string, teamId: string, scheduledAt: Date, appointmentId: string): Promise<boolean> {
 *     const key = this.generateKey(businessId, teamId, scheduledAt);
 *     const existing = await this.get(key);
 *     if (existing) return false;
 *
 *     await this.set(key, appointmentId, this.config.defaultTTL);
 *     return true;
 *   }
 * }
 * ```
 */
export abstract class BaseRedisRepository<T = any> {
  protected readonly logger = new Logger(this.constructor.name);

  constructor(
    protected readonly cacheManager: Cache,
    protected readonly config: BaseRedisRepositoryConfig,
  ) {}

  /**
   * Generate Redis key for the entity
   *
   * This method MUST be implemented by subclasses to define
   * how keys are generated from entity parameters.
   *
   * @param params - Parameters to generate key from
   * @returns Redis key (without prefix - prefix is added automatically)
   */
  protected abstract generateKey(...params: any[]): string;

  /**
   * Build full Redis key with prefix
   *
   * @param key - Key generated by generateKey()
   * @returns Full key with prefix
   */
  private buildFullKey(key: string): string {
    return `${this.config.keyPrefix}:${key}`;
  }

  /**
   * Get value by key
   *
   * @param key - Key generated by generateKey()
   * @returns Value or null if not found
   */
  async get(key: string): Promise<T | null> {
    try {
      const fullKey = this.buildFullKey(key);
      const value = await this.cacheManager.get<T>(fullKey);

      if (value === null || value === undefined) {
        this.logger.debug(`Key not found: ${fullKey}`);
        return null;
      }

      this.logger.debug(`Retrieved from Redis: ${fullKey}`);
      return value;
    } catch (error: any) {
      this.logger.error(`Error getting ${this.config.entityName} from Redis:`, error);
      throw error;
    }
  }

  /**
   * Set value with optional TTL
   *
   * @param key - Key generated by generateKey()
   * @param value - Value to store
   * @param ttl - TTL in seconds (defaults to config.defaultTTL)
   */
  async set(key: string, value: T, ttl?: number): Promise<void> {
    try {
      const fullKey = this.buildFullKey(key);
      const effectiveTTL = ttl ?? this.config.defaultTTL;

      // cache-manager expects TTL in milliseconds
      await this.cacheManager.set(fullKey, value, effectiveTTL * 1000);

      this.logger.debug(
        `Set in Redis: ${fullKey} (TTL: ${effectiveTTL}s)`,
      );
    } catch (error: any) {
      this.logger.error(`Error setting ${this.config.entityName} in Redis:`, error);
      throw error;
    }
  }

  /**
   * Delete key
   *
   * @param key - Key generated by generateKey()
   */
  async delete(key: string): Promise<void> {
    try {
      const fullKey = this.buildFullKey(key);
      await this.cacheManager.del(fullKey);
      this.logger.debug(`Deleted from Redis: ${fullKey}`);
    } catch (error: any) {
      this.logger.error(`Error deleting ${this.config.entityName} from Redis:`, error);
      throw error;
    }
  }

  /**
   * Check if key exists
   *
   * @param key - Key generated by generateKey()
   * @returns true if key exists, false otherwise
   */
  async exists(key: string): Promise<boolean> {
    try {
      const fullKey = this.buildFullKey(key);
      const value = await this.cacheManager.get(fullKey);
      const exists = value !== null && value !== undefined;

      this.logger.debug(`Key ${fullKey} exists: ${exists}`);
      return exists;
    } catch (error: any) {
      this.logger.error(`Error checking existence of ${this.config.entityName} in Redis:`, error);
      throw error;
    }
  }

  /**
   * Set value with expiration at specific date/time
   *
   * Calculates TTL from current time to expiresAt.
   * If expiresAt is in the past, sets TTL to 0 (immediate expiration).
   *
   * @param key - Key generated by generateKey()
   * @param value - Value to store
   * @param expiresAt - Date when key should expire
   */
  async setWithExpiration(key: string, value: T, expiresAt: Date): Promise<void> {
    try {
      const now = new Date();
      const ttlMs = expiresAt.getTime() - now.getTime();
      const ttlSeconds = Math.max(0, Math.floor(ttlMs / 1000));

      await this.set(key, value, ttlSeconds);

      this.logger.debug(
        `Set in Redis with expiration: ${this.buildFullKey(key)} (expires at ${expiresAt.toISOString()}, TTL: ${ttlSeconds}s)`,
      );
    } catch (error: any) {
      this.logger.error(`Error setting ${this.config.entityName} with expiration in Redis:`, error);
      throw error;
    }
  }

  /**
   * Get remaining TTL for a key
   *
   * Note: This requires direct access to Redis client (not available in cache-manager).
   * Subclasses should override if they need this functionality.
   *
   * @param key - Key generated by generateKey()
   * @returns TTL in seconds, or null if key doesn't exist
   */
  async getTTL(key: string): Promise<number | null> {
    this.logger.warn('getTTL() not implemented - requires direct Redis client access');
    return null;
  }
}
